"""Add firebase_uid

Revision ID: 71500d2b5416
Revises: f42c6cf69d4a
Create Date: 2026-02-19 15:46:14.774446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71500d2b5416'
down_revision = 'f42c6cf69d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_firebase_uid'), ['firebase_uid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_firebase_uid'))
        batch_op.drop_column('firebase_uid')

    # ### end Alembic commands ###
