"""Add gender field to User

Revision ID: 989257f49421
Revises: db48e996226a
Create Date: 2026-02-19 16:58:49.213672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989257f49421'
down_revision = 'db48e996226a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
