"""Add profile fields to User

Revision ID: db48e996226a
Revises: 71500d2b5416
Create Date: 2026-02-19 16:48:44.104798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db48e996226a'
down_revision = '71500d2b5416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_profile_complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_profile_complete')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
